; DragRacer_ThingPlus_ProMicroRP2040_HUSKYLENS_SCMD
; Source: Robots/LineFollower/DragRacer_ThingPlus_ProMicroRP2040_HUSKYLENS_SCMD
; https://github.com/dancingevilgenius/Robots.git

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = sparkfun-promicro-rp2040

[env:sparkfun-promicro-rp2040]
extends = common
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = sparkfun_promicrorp2040
framework = arduino

lib_deps =
    https://github.com/adafruit/Adafruit_NeoPixel.git
