; ZioUltrasonicSensor
; Source: Robots/ConeStalker/ZioUltrasonicSensor
; https://github.com/dancingevilgenius/Robots.git
; Board: SparkFun RedBoard Turbo (SAMD51) — Wire1 / Rev4 ConeStalker hardware

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = sparkfun-redboard-turbo

[env:sparkfun-redboard-turbo]
extends = common
platform = atmelsam
board = sparkfun_redboard_turbo
framework = arduino

lib_deps =
    https://github.com/adafruit/Adafruit-GFX-Library.git
    https://github.com/adafruit/Adafruit_SSD1306.git
    https://github.com/adafruit/Adafruit_BusIO.git
