; MiniSumo_Propmaker_MUX
; Source: Robots/MiniSumo/MiniSumo_Propmaker_MUX
; https://github.com/dancingevilgenius/Robots.git

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = adafruit-feather-prop-maker

[env:adafruit-feather-prop-maker]
extends = common
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_prop_maker
framework = arduino

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    pololu/QTRSensors @ ^3.0.0
    sparkfun/SparkFun VL53L1X VL53L4 CX VL53L3 CX Distance Sensor @ ^1.2.5
    sparkfun/SparkFun I2C Mux Arduino Library @ ^1.0.3
