[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    SCMD_config
    SparkFun_VL53L5CX_Library
    Wire
    SparkFun_Alphanumeric_Display
    SCMD
    MedianFilterLib2
