[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    Wire
    QTRSensors
    SparkFun_VL53L1X
    Adafruit_NeoPixel
    SparkFun_I2C_Mux_Arduino_Library
    FS_MX1508
