[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    DFRobot_MatrixLidar
    ESPAsyncWebServer
    Adafruit_IS31FL3741
    Wire
    Arduino
    ArduinoJson
    WiFi
    AsyncTCP
    LittleFS
