[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    SCMD_config
    DFRobot_MatrixLidar
    Wire
    Arduino
    SparkFun_Alphanumeric_Display
    SCMD
    stdint
