; MiniSumo QT Py ESP32 Pico - 8x8 Lidar + 13x9 LED Matrix + SCMD
; Source: R:\Robots\MiniSumo\MiniSumo_QT_PY_Pico_8x8_13x9_SCMD

[env:adafruit_qtpy_esp32pico]
platform = espressif32
board = adafruit_qtpy_esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 8MB
board_build.psram = enabled
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv

; Custom SCMD: lib/Serial_Controlled_Motor_Driver -> R:\ArduinoLibraryExamples\libraries\Serial_Controlled_Motor_Driver
lib_deps =
    bblanchon/ArduinoJson @ ^7.4.3
    https://github.com/ESP32Async/AsyncTCP.git#v3.4.10
    https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.11.0
    adafruit/Adafruit IS31FL3741 Library
    adafruit/Adafruit BusIO
    https://github.com/DFRobot/DFRobot_MatrixLidar.git

build_flags =
    -DCORE_DEBUG_LEVEL=0