; RCSumo_ESP32_PS3
; Source: Robots/MiniSumo/RCSumo_ESP32_PS3
; https://github.com/dancingevilgenius/Robots.git

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = adafruit-feather-esp32

[env:adafruit-feather-esp32]
extends = common
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
upload_speed = 921600

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    pololu/QTRSensors @ ^3.0.0
    sparkfun/SparkFun VL53L1X VL53L4 CX VL53L3 CX Distance Sensor @ ^1.2.5
    sparkfun/SparkFun I2C Mux Arduino Library @ ^1.0.3
