; DragRacer_Inland_OSOYOO
; Source: Robots/LineFollower/DragRacer_Inland_OSOYOO
; https://github.com/dancingevilgenius/Robots.git

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = esp32dev

[env:esp32dev]
extends = common
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
