; MiniSumo_ESP32_C3_8x8_LedMatrix_Web_SCMD
; Source: Robots/MiniSumo/MiniSumo_ESP32_C3_8x8_LedMatrix_Web_SCMD
; https://github.com/dancingevilgenius/Robots.git

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = esp32-c3-minisumo-web

[env:esp32-c3-minisumo-web]
extends = common
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.3
    https://github.com/ESP32Async/AsyncTCP.git#v3.4.10
    https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.11.0
    https://github.com/DFRobot/DFRobot_MatrixLidar.git
    adafruit/Adafruit IS31FL3741 Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit NeoPixel @ ^1.12.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
