; MiniSumo_QT_PY_8x8_AN_SCMD
; Source: Robots/MiniSumo/MiniSumo_QT_PY_8x8_AN_SCMD
; https://github.com/dancingevilgenius/Robots.git

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = adafruit_qtpy_esp32s3

[env:adafruit_qtpy_esp32s3]
extends = common
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
upload_speed = 921600

lib_deps =
    sparkfun/SparkFun VL53L5CX Library @ ^1.0.3
    sparkfun/SparkFun Qwiic Alphanumeric Display @ ^1.0.3