[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    Adafruit_TestBed
    Wire
    Arduino
    Adafruit_MAX1704X
    SparkFun_Alphanumeric_Display
    qwstpad
