[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    ESPAsyncWebServer
    ESPAsyncTCP
    AsyncJson
    Arduino
    ESP8266WiFi
    WebServer
    ArduinoJson
    AsyncMessagePack
    WiFi
    AsyncTCP
    LittleFS
