; QwiicMotorDriverTest
; Source: Robots/ConeStalker/QwiicMotorDriverTest
; https://github.com/dancingevilgenius/Robots.git
; Board: Arduino Uno R4 WiFi

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = uno-r4-wifi

[env:uno-r4-wifi]
extends = common
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
