; Rev4_VL53L1X_ReadDistance
; Source: Robots/ConeStalker/Rev4_VL53L1X_ReadDistance
; https://github.com/dancingevilgenius/Robots.git
; Board: SparkFun RedBoard Turbo (SAMD51) — Wire1 / Rev4 ConeStalker hardware

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = sparkfun-redboard-turbo

[env:sparkfun-redboard-turbo]
extends = common
platform = atmelsam
board = sparkfun_redboard_turbo
framework = arduino
