[env:sparkfun_thing_plus_rp2040]
platform = raspberrypi
board = sparkfun_thing_plus_rp2040
framework = arduino
monitor_speed = 115200
lib_deps =
    SparkFun_u-blox_GNSS_v3
    SparkFun_u-blox_GNSS_Arduino_Library
