; MiniSumo_RP2040_8x8_SCMD_BLE
; Source: Robots/MiniSumo/MiniSumo_RP2040_8x8_SCMD_BLE
; https://github.com/dancingevilgenius/Robots.git
; Board: SparkFun Thing Plus RP2040 (Earle Philhower core via maxgerhardt platform)

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = sparkfun-thing-plus-rp2040

[env:sparkfun-thing-plus-rp2040]
extends = common
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = sparkfun_thingplusrp2040
framework = arduino

lib_deps =
    https://github.com/DFRobot/DFRobot_MatrixLidar.git
    adafruit/Adafruit IS31FL3741 Library
    adafruit/Adafruit BusIO
