; ESP32-C3 Pro Micro - Web Server D-Pad
; Source: ArduinoSketches/ESP32/ESP32_C3_ProMicro_WebServer_DPad

[platformio]
extra_configs = ../../platformio.shared.ini
default_envs = esp32-c3-promicro-dpad

[env:esp32-c3-promicro-dpad]
extends = common
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_filters = direct
monitor_eol = CRLF

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.3

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
