[env:uno]
platform = espressif32
board = adafruit_qtpy_esp32
framework = arduino
monitor_speed = 115200
lib_deps =
    SCMD_config
    DFRobot_MatrixLidar
    ESPAsyncWebServer
    Adafruit_IS31FL3741
    Wire
    Arduino
    ArduinoJson
    SCMD
    WiFi
    AsyncTCP
    LittleFS
    stdint
